bb="T_EDUCATION_BG_INFO, T_HR_CATEGORY_DISTRIBUTION, T_HR_EMPLOYMENT_EDUCATION, T_HR_FROM_RATIO, T_HR_HISTORICAL_POPULATION, T_HR_INDUSTRY_RATIO, T_HR_INDUSTRY_RATIO_Copy, T_HR_MAP_DISTRIBUTION, T_HR_MAP_DISTRIBUTION_copy, T_HR_OUTSTANDING_TALENT_INFO, T_HR_TALENT_CONSTRUCTION, T_HR_URBAN_BY_PUBLIC_GOV, T_HR_URBAN_BY_REGISTRATION, T_HR_URBAN_BY_SECTOR_REGION, T_PERSON_ATTACHMENT, T_PERSON_BASE_INFO, T_PERSON_DISTRIBUTION, T_PERSON_EXPER_INFO, T_PROFE_INFO, T_RESEARCH_INFO"
aa="T_CMP_AFFILIATE, T_CMP_AREA_SUM, T_CMP_ATTACHMENT, T_CMP_BASEINFO_MODIFY, T_CMP_BASICINFO, T_CMP_BID, T_CMP_BOND, T_CMP_COPYRIGHT, T_CMP_COURT_ANNOUNCEMENT, T_CMP_DISHONEST, T_CMP_EXECUTED, T_CMP_HEARING_ANNOUNCEMENT, T_CMP_INVESTMENT, T_CMP_LAWSUIT, T_CMP_MARKETINFO, T_CMP_PARNTNER, T_CMP_PATENT, T_CMP_RISK_AO, T_CMP_RISK_EP, T_CMP_SE, T_CMP_TAX_CREDIT_RATING, T_CMP_TRADEMARK"
la=bb.split(",")
for i in la:
    print(i)
